import type { EditorField } from "@/components/admin-editor";
import { coverChoices } from "@/content/artwork";
import {
  CLASSES,
  DAYS,
  FACTIONS,
  PLAYSTYLES,
  REGIONS,
  RULESETS,
} from "@/lib/config";

export const settingsFields: EditorField[] = [
  {
    name: "discordInvite",
    label: "Main Discord invite",
    type: "url",
    full: true,
    hint: "Every Join Discord button uses this invitation. Use a permanent invite.",
  },
  {
    name: "backupInvite",
    label: "Backup Discord invite",
    type: "url",
    full: true,
  },
  {
    name: "memberCount",
    label: "Community member count",
    hint: "Leave blank to avoid claiming a manual count. Live Discord counts appear on the Discord page.",
  },
  {
    name: "raidsHosted",
    label: "Organizer raids hosted",
    hint: "Historical organizer experience, not raids hosted by this new server.",
  },
  {
    name: "heroDescription",
    label: "Homepage introduction",
    type: "textarea",
    required: true,
    full: true,
    maxLength: 240,
  },
  { name: "announcement", label: "Announcement", full: true, maxLength: 150 },
  {
    name: "announcementHref",
    label: "Announcement page",
    required: true,
    hint: "A local page, such as /discord or /guides.",
  },
  { name: "contactEmail", label: "Public contact email", type: "email" },
  {
    name: "discordOnboarding",
    label: "Discord channels and onboarding",
    type: "textarea",
    full: true,
    maxLength: 4000,
    hint: "Public Markdown. Use the actual channel names, roles and languages. Blank hides this section.",
  },
  {
    name: "discordOrganizers",
    label: "Public organizer details",
    type: "textarea",
    full: true,
    maxLength: 2000,
    hint: "Consenting handles, EU/NA responsibilities and actual availability. Do not include private staff information.",
  },
  {
    name: "googleVerification",
    label: "Google verification value",
    full: true,
    maxLength: 200,
    hint: "Optional HTML verification value for a URL-prefix property. A Google Domain property requires DNS TXT verification.",
  },
  {
    name: "bingVerification",
    label: "Bing verification value",
    full: true,
    maxLength: 200,
    hint: "The content value from Bing's msvalidate.01 tag. Adding it does not itself verify ownership.",
  },
];
export const guideFields: EditorField[] = [
  { name: "title", label: "Title", required: true, full: true, maxLength: 140 },
  { name: "slug", label: "URL slug", required: true, maxLength: 100 },
  {
    name: "category",
    label: "Category",
    type: "select",
    options: [
      "Getting started",
      "Guilds",
      "Community",
      "Safety",
      "Addons",
      "News",
    ],
  },
  {
    name: "excerpt",
    label: "Excerpt",
    type: "textarea",
    full: true,
    required: true,
    maxLength: 320,
  },
  { name: "author", label: "Author", required: true },
  {
    name: "coverImage",
    label: "Cover image",
    type: "select",
    options: coverChoices,
  },
  {
    name: "content",
    label: "Article (Markdown)",
    type: "textarea",
    full: true,
    required: true,
    maxLength: 100000,
  },
  { name: "metaTitle", label: "Search title (optional)", maxLength: 80 },
  {
    name: "metaDescription",
    label: "Search description (optional)",
    maxLength: 180,
  },
  {
    name: "published",
    label: "Published and visible to visitors",
    type: "checkbox",
    full: true,
  },
];
export const guildFields: EditorField[] = [
  { name: "name", label: "Guild name", required: true },
  {
    name: "status",
    label: "Status",
    type: "select",
    options: ["pending", "approved", "hidden", "rejected"],
  },
  { name: "region", label: "Region", type: "select", options: REGIONS },
  { name: "realm", label: "Realm", required: true },
  { name: "faction", label: "Faction", type: "select", options: FACTIONS },
  { name: "ruleset", label: "Activity", type: "select", options: RULESETS },
  { name: "language", label: "Language", required: true },
  {
    name: "playstyle",
    label: "Playstyle",
    type: "select",
    options: PLAYSTYLES,
  },
  {
    name: "raidDays",
    label: "Raid days",
    type: "choices",
    options: DAYS,
    full: true,
  },
  { name: "raidTime", label: "Raid time and time zone", required: true },
  { name: "lootSystem", label: "Loot system", required: true },
  {
    name: "recruitingClasses",
    label: "Recruiting classes",
    type: "choices",
    options: CLASSES,
    full: true,
  },
  {
    name: "description",
    label: "Description",
    type: "textarea",
    required: true,
    full: true,
    maxLength: 8000,
  },
  { name: "contactDiscord", label: "Discord contact", required: true },
  { name: "inviteUrl", label: "Discord invite", type: "url" },
  { name: "websiteUrl", label: "Website", type: "url" },
  { name: "featured", label: "Feature this guild", type: "checkbox" },
];
export const staffFields: EditorField[] = [
  { name: "name", label: "Display name", required: true },
  { name: "email", label: "Email", type: "email", required: true },
  {
    name: "role",
    label: "Role",
    type: "select",
    options: ["owner", "admin", "moderator", "editor"],
  },
  {
    name: "password",
    label: "New password",
    type: "password",
    hint: "At least 16 characters. Leave blank to keep the current password.",
  },
  { name: "active", label: "Account is active", type: "checkbox" },
];
